version: 2.1
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          DOCKER_TAG="$CIRCLE_BRANCH-$CIRCLE_SHA1"
          DOCKER_IMAGE="vfeskov/gitpunch:$DOCKER_TAG"

          docker build -t $DOCKER_IMAGE .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $DOCKER_IMAGE

          bash ./deploy-docker-image.sh

workflows:
  Deploy:
    jobs:
      - deploy
