version: 2.1
jobs:
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          export DOCKER_TAG="$CIRCLE_BRANCH-$CIRCLE_SHA1"
          export DOCKER_IMAGE="vfeskov/gitpunch:$DOCKER_TAG"

          docker build -t $DOCKER_IMAGE .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $DOCKER_IMAGE

          ./.circleci/deploy-docker-image.sh

workflows:
  Deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
