version: 2.1
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t "vfeskov/gitpunch:$CIRCLE_BRANCH-$CIRCLE_SHA1" .
          docker push "vfeskov/gitpunch:$CIRCLE_BRANCH-$CIRCLE_SHA1"
workflows:
  Build:
    jobs:
      - build
